USE DATOS_PERSONALES;
DELIMITER //
CREATE PROCEDURE Consulta_byIde
(
	IN _ide INT
)
BEGIN
	SELECT DATOS_PERSONALES.cod, DATOS_GENERALES.primerNombre, 
	DATOS_GENERALES.primerApellido, PROCEDENCIA.pais, CONTACTO.numero, 
	DATOS_ELECTRONICOS.correo 
	FROM DATOS_PERSONALES, DATOS_GENERALES, DATOS_IMPORTANTES, 
	PROCEDENCIA, DATOS_PERSONALES_CONTACTO, CONTACTO, DATOS_ELECTRONICOS 
	WHERE DATOS_PERSONALES.cod=_ide 
	AND DATOS_PERSONALES.datosGeneralCod=DATOS_GENERALES.cod 
	AND DATOS_PERSONALES.datosImportCod=DATOS_IMPORTANTES.cod 
	AND DATOS_IMPORTANTES.procedenciaCod=PROCEDENCIA.cod 
	AND DATOS_PERSONALES.cod=DATOS_PERSONALES_CONTACTO.cod 
	AND DATOS_PERSONALES_CONTACTO.contactoCod=CONTACTO.cod 
	AND CONTACTO.contElectronico=DATOS_ELECTRONICOS.cod;
END
//



USE DATOS_PERSONALES;
DELIMITER //
CREATE PROCEDURE Consulta_byNombre
(
	IN _nombre varchar(255)
)
BEGIN
	SELECT DATOS_PERSONALES.cod, DATOS_GENERALES.primerNombre, 
	DATOS_GENERALES.primerApellido, PROCEDENCIA.pais, CONTACTO.numero, 
	DATOS_ELECTRONICOS.correo 
	FROM DATOS_PERSONALES, DATOS_GENERALES, DATOS_IMPORTANTES, 
	PROCEDENCIA, DATOS_PERSONALES_CONTACTO, CONTACTO, DATOS_ELECTRONICOS 
	WHERE DATOS_GENERALES.primerNombre=_nombre
	AND DATOS_PERSONALES.datosGeneralCod=DATOS_GENERALES.cod 
	AND DATOS_PERSONALES.datosImportCod=DATOS_IMPORTANTES.cod 
	AND DATOS_IMPORTANTES.procedenciaCod=PROCEDENCIA.cod 
	AND DATOS_PERSONALES.cod=DATOS_PERSONALES_CONTACTO.cod 
	AND DATOS_PERSONALES_CONTACTO.contactoCod=CONTACTO.cod 
	AND CONTACTO.contElectronico=DATOS_ELECTRONICOS.cod;
END
//
